[package]
name = "filen-sdk-rs"
version = "0.0.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
hex = "0.4.3"
ring = "0.17.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
