[package]
name = "filen-sdk-rs"
version = "0.0.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.7", features = ["blocking"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
