[package]
name = "filen-sdk-rs"
version = "0.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
